### ISSUE TITLE
Create a print function

### ISSUE THREAD

**Issue by dean985** [dean985/wargame#2]
יש ליצור פונקציה שתראה את הלוח

בינתיים: 
יצרתי אקסל בתיקייה docs 
באמצעות האקסל הזה נוכל לתכנן את הבדיקות

**Comment by elonezra** [comment]
נעשה לולאה שתעבור על כל האיברים.
אם האיבר לא null אז תדפיס
אות של סוג החייל מספר השחקן ואם הוא מפקד אז ליידו נספיס 
אות c

**Comment by dean985** [comment]
הפונקציה עובדת
